---
- name: mutipleplaybooks with tags
  hosts: all
  become: true
  tasks:
    - name: install nginx package
      apt:
        name: nginx
        state: present
      tags: nginx  

- name: mutipleplaybooks with tags
  hosts: all
  become: true
  tasks:
    - name: install git
      apt:
        name: git
        state: present
              
      
        