---
- name: mutipleplaybooks with tags
  hosts: all
  become: true
  tasks:
    - name: install nginx package
      apt:
        name: nginx
        state: present

- name: mutipleplaybooks with tags
  hosts: all
  become: true
  tasks:
    - name: install ansible
      apt:
        name: ansible
        state: present
      tags: ansible         
      
        