---
- name: Install and configure NGINX with variables
  hosts: all
  become: true

  vars:
    package_name: nginx
    service_name: nginx
    homepage_path: /var/www/html/index.html
    homepage_title: "Welcome to Ansible Web Server"
    homepage_body: "This page was created using Ansible variables."

  tasks:
    - name: Install NGINX
      apt:
        name: "{{ package_name }}"
        state: present

    - name: Start and enable NGINX service
      systemd:
        name: "{{ service_name }}"
        enabled: true
        state: started

    - name: Create a custom index.html
      copy:
        dest: "{{ homepage_path }}"
        content: |
          <html>
          <head><title>{{ homepage_title }}</title></head>
          <body>
            <h1>{{ homepage_title }}</h1>
            <p>{{ homepage_body }}</p>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'
